In [1]:
import tensorflow as tf 
import numpy as np 
print("tensorflow version:",tf.__version__)

tensorflow version: 2.2.0


In [2]:
tf.config.experimental_run_functions_eagerly(True)
print("eager execution is: " ,tf.executing_eagerly())

eager execution is:  True


In [3]:
a=tf.constant([[1,2],[3,4]])
a.numpy()

array([[1, 2],
       [3, 4]])

In [4]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [5]:
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
tf.constant(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [7]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [8]:
tf.constant(1.0,dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [9]:
import numpy as np 
tf.constant(np.array([1,2]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [10]:
'''numpy创建浮点数数组时，默认的浮点型是64位浮点数。
当使用NumPy数组创建张量时，TensorFlow会接受数组
元素的数据类型，使用64位浮点数保存数据。'''
tf.constant(np.array([1.0,2.0]))

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1., 2.])>

In [11]:
#指明数据类型为32位浮点
tf.constant(np.array([1.0,2.0]),dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [12]:
#tf.cast()函数：改变张量中元素的数据类
a=tf.constant(np.array([1,2]))
b=tf.cast(a,dtype=tf.float16)
b.dtype

tf.float16

In [13]:
a=tf.constant(123456789,dtype=tf.int32)
tf.cast(a,tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [14]:
# 参数为布尔型
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [15]:
a=tf.constant([True,False])
tf.cast(a,dtype=tf.int16)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 0], dtype=int16)>

In [16]:
a=tf.constant([0,1,2,3,4,5,6.-1])
tf.cast(a,dtype=tf.bool)

<tf.Tensor: shape=(7,), dtype=bool, numpy=array([False,  True,  True,  True,  True,  True,  True])>

In [17]:
tf.constant("hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [18]:
# tf.convert_to_tensor()函数创建张量
na=np.arange(12).reshape(3,4)
ta=tf.convert_to_tensor(na)
type(na)

numpy.ndarray

In [19]:
type(ta)

tensorflow.python.framework.ops.EagerTensor

In [20]:
tf.is_tensor(ta)

True

In [21]:
isinstance(ta,tf.Tensor)

True

In [22]:
# 创建全0张量和全1张量
tf.ones(shape=(9,9))

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros([9])

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [24]:
tf.ones([9,1],dtype=tf.int32)

<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])>

In [25]:
#创建元素值都相同的张量—— tf.fill()函数
tf.fill([2,2],value=9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]])>

In [26]:
tf.constant(value=9,shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [27]:
tf.fill(dims=[2,3],value="sss")

<tf.Tensor: shape=(2, 3), dtype=string, numpy=
array([[b'sss', b'sss', b'sss'],
       [b'sss', b'sss', b'sss']], dtype=object)>

In [34]:
# 创建随机数张量——正态分布
#tf.random.normal( shape, mean, stddev, dtype )
#形状 均值 标准差 数据类型
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0460263 ,  1.0982687 ],
       [ 0.5950667 ,  0.20979917]], dtype=float32)>

In [35]:
tf.random.normal([3,3,3],mean=0.0,stddev=2.0)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-1.5134152 ,  0.6807063 , -1.9976131 ],
        [-0.92279243, -0.898463  ,  2.8027673 ],
        [ 3.270326  ,  0.14157021, -3.9366379 ]],

       [[ 1.5144184 , -0.3548147 , -0.9226826 ],
        [-0.39161283, -0.6105048 , -2.9959815 ],
        [ 2.6258917 , -1.995134  , -2.5341349 ]],

       [[-0.8109242 ,  1.6404287 , -0.11751053],
        [ 0.32380623, -2.9953182 , -1.9018034 ],
        [ 0.89317805,  3.8696115 ,  1.3372667 ]]], dtype=float32)>

In [37]:
#截断正态分布
tf.random.truncated_normal([3,3,3],mean=0.0,stddev=1.0)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 0.6459214 , -0.37942213,  0.5220066 ],
        [ 1.06337   ,  0.9679726 ,  1.6197397 ],
        [ 0.89440924,  0.45701396,  0.46316132]],

       [[-0.77026165, -0.87071157, -1.6121769 ],
        [ 1.4857898 , -1.7573879 , -0.22993977],
        [ 0.44018653,  1.5500519 , -1.2760416 ]],

       [[ 0.38229427,  0.2903009 , -0.31871733],
        [-1.1707617 ,  0.21660747, -0.370126  ],
        [ 0.35755238,  1.8674486 , -1.7497528 ]]], dtype=float32)>

In [44]:
#设置随机种子tf.random.set_seed()
tf.random.set_seed(8)
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988]], dtype=float32)>

In [45]:
#均匀分布张量——tf.random.uniform()函数
tf.random.uniform(shape=[3,3],minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 8, 3],
       [9, 5, 1],
       [8, 6, 1]])>

In [52]:
# 随机打乱——tf.random.shuffle()函数
x=[[1,2],[3,4],[5,6]] 
tf.random.shuffle(x) #参数为张量，随机打乱第一维

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]])>

In [53]:
y=[1,2,3,4,5]
tf.random.shuffle(y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 5, 4, 3])>

In [55]:
z=np.arange(5)
tf.random.shuffle(z)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 1, 2, 0, 4])>

In [57]:
# 创建序列——tf.range()函数
tf.range(10)
tf.range(10,delta=2)
tf.range(1,10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [ ]:
# 类 型 函 数 功 能
# 常量
# tf.constant(value, dtype, shape) 创建张量
# tf.convert_to_tensor() 创建张量
# tf.zeros(shape, dtype = tf.float32) 创建全0张量
# tf.ones(shape, dtype = tf.float32) 创建全1张量
# tf.fill(shape, value) 创建元素值全部相同的张量
# 随机量
# tf.random.normal() 创建元素取值符合正态分布的张量
# tf.random.truncated_normal( shape, mean, stddev, dtype ) 创建元素取值符合截断正态分布的张量
# tf.random.uniform(shape,minval,maxval, dtype) 创建元素取值符合均匀分布的张量
# 序列 
# tf.range(起始数字,结束数字,步长) 创建元素取值为整数序列的张量

In [59]:
#  Tensor对象的属性——ndim、shape、dtype
a=tf.constant([[1,2],[3,4]])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)



tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
2
<dtype: 'int32'>
(2, 2)


In [66]:
#  获得Tensor对象的形状、元素总数和维度
a=tf.constant([[1,2],[3,4]])
print(tf.shape(a))
print(tf.size(a))
print(tf.rank(a))

tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
